// <auto-generated />
using CypherBot.Core.DataAccess.Repos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CypherBot.Core.DataAccess.Migrations
{
    [DbContext(typeof(CypherContext))]
    partial class CypherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CypherBot.Core.Models.Artifact", b =>
                {
                    b.Property<int>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Depletion")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Effect")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Form")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Genre")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("LevelBonus")
                        .HasColumnType("integer");

                    b.Property<int>("LevelDie")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("ArtifactId");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("CypherBot.Core.Models.ArtifactQuirk", b =>
                {
                    b.Property<int>("ArtifactQuirkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EndRange")
                        .HasColumnType("integer");

                    b.Property<string>("Quirk")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("StartRange")
                        .HasColumnType("integer");

                    b.HasKey("ArtifactQuirkId");

                    b.ToTable("ArtifactQuirks");
                });

            modelBuilder.Entity("CypherBot.Core.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descriptor")
                        .HasColumnType("text");

                    b.Property<string>("Focus")
                        .HasColumnType("text");

                    b.Property<int>("IntPool")
                        .HasColumnType("integer");

                    b.Property<int>("MightPool")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Player")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("RecoveryDie")
                        .HasColumnType("integer");

                    b.Property<int>("RecoveryMod")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedPool")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterAbility", b =>
                {
                    b.Property<int>("CharacterAbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("CharacterAbilityId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAbilities");
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterArtifact", b =>
                {
                    b.Property<int>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Depletion")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Effect")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Form")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<bool>("IsIdentified")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("LevelBonus")
                        .HasColumnType("integer");

                    b.Property<int>("LevelDie")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Quirk")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("ArtifactId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterArtifacts");
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterCypher", b =>
                {
                    b.Property<int>("CypherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Effect")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("EffectOption")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Form")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("IsIdentified")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("LevelBonus")
                        .HasColumnType("integer");

                    b.Property<int>("LevelDie")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Type")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("CypherId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterCyphers");
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("InventoryId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterInventories");
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterRecoveryRoll", b =>
                {
                    b.Property<int>("RecoveryRollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("RollName")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("RecoveryRollId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterRecoveryRolls");
                });

            modelBuilder.Entity("CypherBot.Core.Models.Cypher", b =>
                {
                    b.Property<int>("CypherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Effect")
                        .HasColumnType("text");

                    b.Property<int>("LevelBonus")
                        .HasColumnType("integer");

                    b.Property<int>("LevelDie")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Type")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("CypherId");

                    b.ToTable("Cyphers");
                });

            modelBuilder.Entity("CypherBot.Core.Models.CypherEffectOption", b =>
                {
                    b.Property<int>("EffectOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CypherId")
                        .HasColumnType("integer");

                    b.Property<string>("EffectDescription")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("EndRange")
                        .HasColumnType("integer");

                    b.Property<int>("StartRange")
                        .HasColumnType("integer");

                    b.HasKey("EffectOptionId");

                    b.HasIndex("CypherId");

                    b.ToTable("CypherEffectOptions");
                });

            modelBuilder.Entity("CypherBot.Core.Models.CypherFormOption", b =>
                {
                    b.Property<int>("FormOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CypherId")
                        .HasColumnType("integer");

                    b.Property<string>("Form")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FormDescription")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("FormOptionId");

                    b.HasIndex("CypherId");

                    b.ToTable("CypherFormOptions");
                });

            modelBuilder.Entity("CypherBot.Core.Models.Descriptor", b =>
                {
                    b.Property<int>("DescriptorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("DescriptorId");

                    b.ToTable("Descriptors");
                });

            modelBuilder.Entity("CypherBot.Core.Models.DescriptorAbility", b =>
                {
                    b.Property<int>("DescriptorAbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("DescriptorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("DescriptorAbilityId");

                    b.HasIndex("DescriptorId");

                    b.ToTable("DescriptorAbilities");
                });

            modelBuilder.Entity("CypherBot.Core.Models.Focus", b =>
                {
                    b.Property<int>("FocusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("FocusId");

                    b.ToTable("Foci");
                });

            modelBuilder.Entity("CypherBot.Core.Models.FocusAbility", b =>
                {
                    b.Property<int>("FocusAbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("FocusId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("FocusAbilityId");

                    b.HasIndex("FocusId");

                    b.ToTable("FociAbilities");
                });

            modelBuilder.Entity("CypherBot.Core.Models.Oddity", b =>
                {
                    b.Property<int>("OddityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("OddityDescription")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("OddityId");

                    b.ToTable("Oddities");
                });

            modelBuilder.Entity("CypherBot.Core.Models.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("IntellectStartingPool")
                        .HasColumnType("integer");

                    b.Property<int>("MightStartingPool")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SpeedStartingPool")
                        .HasColumnType("integer");

                    b.HasKey("TypeId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("CypherBot.Core.Models.TypeAbility", b =>
                {
                    b.Property<int>("TypeAbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("TypeAbilityId");

                    b.HasIndex("TypeId");

                    b.ToTable("TypeAbilities");
                });

            modelBuilder.Entity("CypherBot.Core.Models.UnidentifiedArtifact", b =>
                {
                    b.Property<int>("UnidentifiedArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Depletion")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Effect")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Form")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Genre")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("IsIdentified")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelBonus")
                        .HasColumnType("integer");

                    b.Property<int>("LevelDie")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Quirk")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UnidentifiedArtifactKey")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("UnidentifiedArtifactId");

                    b.ToTable("UnidentifiedArtifacts");
                });

            modelBuilder.Entity("CypherBot.Core.Models.UnidentifiedCypher", b =>
                {
                    b.Property<int>("UnidentifiedCypherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Effect")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("EffectOption")
                        .HasColumnType("text");

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.Property<bool>("IsIdentified")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelBonus")
                        .HasColumnType("integer");

                    b.Property<int>("LevelDie")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Type")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UnidentifiedCypherKey")
                        .HasColumnType("varchar(10)");

                    b.HasKey("UnidentifiedCypherId");

                    b.ToTable("UnidentifiedCyphers");
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterAbility", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Character", "Character")
                        .WithMany("Abilities")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterArtifact", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Character", "Character")
                        .WithMany("Artifacts")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterCypher", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Character", "Character")
                        .WithMany("Cyphers")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterInventory", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CypherBot.Core.Models.CharacterRecoveryRoll", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Character", "Character")
                        .WithMany("RecoveryRolls")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CypherBot.Core.Models.CypherEffectOption", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Cypher", "Cypher")
                        .WithMany("EffectOptions")
                        .HasForeignKey("CypherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CypherBot.Core.Models.CypherFormOption", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Cypher", "Cypher")
                        .WithMany("Forms")
                        .HasForeignKey("CypherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CypherBot.Core.Models.DescriptorAbility", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Descriptor", "Descriptor")
                        .WithMany("DescriptorAbilities")
                        .HasForeignKey("DescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CypherBot.Core.Models.FocusAbility", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Focus", "Focus")
                        .WithMany("FocusAbilities")
                        .HasForeignKey("FocusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CypherBot.Core.Models.TypeAbility", b =>
                {
                    b.HasOne("CypherBot.Core.Models.Type", "Type")
                        .WithMany("TypeAbilities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
